// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldukohhvxlfbeiysjayg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdWtvaGh2eGxmYmVpeXNqYXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTgyNzIsImV4cCI6MjA2Nzg5NDI3Mn0.uO42JcUAP0eh-gkrpq-eM9OHgtTPEcUANTN2AVjGG6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});